const movieList=[
  {
    "id": 1,
    "title": "Inception",
    "description": "A skilled thief is given a chance at redemption if he can successfully perform inception: planting an idea into someone's subconscious.",
    "genre": ["Sci-Fi", "Thriller"],
    "director": "Christopher Nolan",
    "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    "releaseDate": "2010-07-16",
    "rating": 8.8,
    "duration": 148,
    "language": "English",
    "image":"https://m.media-amazon.com/images/I/91G0gTLz6GL._AC_UF1000,1000_QL80_.jpg",
    "backgroundImage":"https://variety.com/wp-content/uploads/2023/07/MCDINCE_EC027.jpg",
  },
  {
    "id": 2,
    "title": "The Dark Knight",
    "description": "Batman faces the Joker, a criminal mastermind who wants to bring chaos to Gotham City.",
    "genre": ["Action", "Crime", "Drama"],
    "director": "Christopher Nolan",
    "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "releaseDate": "2008-07-18",
    "rating": 9.0,
    "duration": 152,
    "language": "English",
    "image":"https://m.media-amazon.com/images/I/61h-H6YpqHL._AC_UF1000,1000_QL80_.jpg",
    "backgroundImage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9nGCAoFOVcVU-za8D1MNUAEdvsBY1h_SOSA&s",
  },
  {
    "id": 3,
    "title": "Interstellar",
    "description": "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    "genre": ["Sci-Fi", "Adventure", "Drama"],
    "director": "Christopher Nolan",
    "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "releaseDate": "2014-11-07",
    "rating": 8.6,
    "duration": 169,
    "language": "English",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBmS2fXunDUEBghw03CwGihiiA4FZlQMgy7Q&s",
    "backgroundImage":"https://today.cofc.edu/wp-content/uploads/sites/3/2014/11/Interstellar-Featured.jpg",
  },
  {
    "id": 4,
    "title": "The Shawshank Redemption",
    "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "genre": ["Drama"],
    "director": "Frank Darabont",
    "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    "releaseDate": "1994-09-23",
    "rating": 9.3,
    "duration": 142,
    "language": "English",
    "image":"https://m.media-amazon.com/images/I/815qtzaP9iL._AC_UF1000,1000_QL80_.jpg",
    "backgroundImage":"https://m.media-amazon.com/images/M/MV5BMTkzMTY0MjE5MV5BMl5BanBnXkFtZTcwODMxNDY3Mw@@._V1_.jpg",
  },
  {
    "id": 5,
    "title": "Parasite",
    "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    "genre": ["Drama", "Thriller"],
    "director": "Bong Joon Ho",
    "cast": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    "releaseDate": "2019-05-30",
    "rating": 8.6,
    "duration": 132,
    "backgroundImage":"https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/10/parasite-poster-thumbnail.jpg",
    "language": "Korean",
    "image":"https://play-lh.googleusercontent.com/bd74_5pOTSmJmdY6-vhkHiuh7Q19-SImDevNhkLPRuWdRvikC2RzonkyznZ29Vs9l9QYg1FO6a2ixIltHIw",
  }
]

export default movieList;